object frmAtualizaDB: TfrmAtualizaDB
  Left = 0
  Top = 0
  BorderStyle = bsNone
  Caption = 'Atualizador'
  ClientHeight = 84
  ClientWidth = 456
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 456
    Height = 84
    Align = alClient
    BevelOuter = bvLowered
    BevelWidth = 3
    BorderWidth = 3
    Color = clBackground
    ParentBackground = False
    TabOrder = 0
    ExplicitWidth = 683
    ExplicitHeight = 280
    object Panel2: TPanel
      Left = 6
      Top = 6
      Width = 444
      Height = 72
      Align = alClient
      BevelOuter = bvNone
      Enabled = False
      ParentBackground = False
      TabOrder = 0
      ExplicitLeft = 12
      ExplicitWidth = 671
      ExplicitHeight = 268
      object Label1: TLabel
        Left = 17
        Top = 24
        Width = 401
        Height = 23
        Caption = 'Atualiza'#231#227'o do Banco de Dados Aguarde...'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Tahoma'
        Font.Style = [fsBold]
        ParentFont = False
      end
    end
  end
end
